# Generated by Django 4.2.1 on 2023-05-29 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prize_draw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_cotas', models.IntegerField()),
                ('preco_cotas', models.FloatField()),
                ('prize_draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prize_draw.prizedraw', verbose_name='Sorteio')),
            ],
        ),
    ]
