# Generated by Django 4.2.1 on 2023-05-29 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('price', models.FloatField()),
                ('qtd_prize_draw', models.IntegerField()),
                ('date_prize_draw', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('image_sorteio', models.ImageField(upload_to='rifa_img/')),
                ('awards', models.ManyToManyField(related_name='premiação', to='awards.awards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
