# Generated by Django 4.2.1 on 2023-05-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize_draw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizedraw',
            name='date_prize_draw',
            field=models.DateTimeField(verbose_name='Data do sorteio'),
        ),
        migrations.AlterField(
            model_name='prizedraw',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='prizedraw',
            name='qtd_prize_draw',
            field=models.IntegerField(verbose_name='Quantidade de sorteio'),
        ),
        migrations.AlterField(
            model_name='prizedraw',
            name='status',
            field=models.BooleanField(verbose_name='status'),
        ),
    ]
