# Generated by Django 4.2.1 on 2023-05-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prize_draw', '0002_alter_prizedraw_date_prize_draw_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prizedraw',
            options={'verbose_name': 'Sorteio', 'verbose_name_plural': 'Sorteios'},
        ),
        migrations.RemoveField(
            model_name='prizedraw',
            name='awards',
        ),
    ]
