# Generated by Django 4.2.1 on 2023-05-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_premio', models.IntegerField()),
                ('descricao_premio', models.CharField(max_length=50)),
            ],
        ),
    ]
