# Generated by Django 4.2.1 on 2023-05-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='descricao_premio',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='numero_premio',
        ),
        migrations.AddField(
            model_name='awards',
            name='description_prize',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição do premio'),
        ),
        migrations.AddField(
            model_name='awards',
            name='prize_number',
            field=models.IntegerField(null=True, verbose_name='Número do premio'),
        ),
    ]
